Add Azure details to the splunk returners
hubblestack/hubble-salt pull request #73
Opened 2017-06-08 23:11 UTC by mew1033

2017-06-08 23:11 UTC, mew1033 commented
So far all we're pulling is the vmId.

2017-06-09 17:05 UTC, basepi commented
I'm wondering if we should combine the details modules into a single `cloud_details.py` module. Thoughts?

2017-06-10 00:38 UTC, mew1033 commented
Not a bad idea. I'm fairly certain we'll be adding in Ethos in the somewhat near future. Might be good to have them all in one.

2017-06-19 17:11 UTC, basepi commented
Would you mind tackling putting them into a single module, @mew1033? That is, if you have time. Would be nice to do it now rather than later.

2017-07-17 19:33 UTC, mew1033 commented
Okay, I think I got them combined. How does it look?

2017-07-24 16:06 UTC, basepi requested changes
Beautifully done. You left some old docs but otherwise I think this looks great!

2017-07-24 16:06 UTC, basepi commented on _returners/cloud_details.py
> +                            event.update({'azure_vmId': azure['azure_vmId']})"""
Can you remove this doc block? It appears to be out of date.

2017-07-24 18:14 UTC, mew1033 commented
Oops, my bad. I had pasted that in there as a reference. Got it removed.

2017-07-24 18:38 UTC, merged